FROM apache/airflow:2.9.3

USER root
RUN apt-get update && apt-get install -y --no-install-recommends git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir \
    joblib \
    scikit-learn \
    pandas \
    numpy \
    mlflow \
    matplotlib \
    pillow \
    prometheus-client \
    evidently